### ISSUE TITLE
Extension with Savings: Undefined function or variable 'invdistr'.

### ISSUE THREAD

**Issue by mhaense1** [amckay/OptStab#1]
It seems the Matlab code for the extension with savings is missing at least one function file. My attempt in running the matlab code by running `FullModel.m` resulted in the following error message:

```
Undefined function or variable 'invdistr'.

Error in initparams_search (line 45)
Params.betaGroupSizes = invdistr(Params.betaSwitch);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in FullModel (line 9)
run('parameters/initparams_search');
```

**Comment by amckay** [comment]
The problem was that setpath was only called in Main.m not in FullModel.m. I added setpath to FullModel.m
